project:
  type: website
  output-dir: docs
  post-render:
    - "cp CNAME docs/CNAME"
    - "touch docs/.nojekyll"

execute:
  freeze: auto

website:
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: "Home"
      - icon: github
        href: https://github.com/stevenhawken
      - icon: twitter
        href: https://twitter.com/stevenhawken
      - icon: linkedin
        href: https://linkedin.com/in/steven-hawken-16204579
      - href: https://ohri.ca/en/find-researcher/steven-hawken
        text: "OHRI Profile"
      - href: http://www.ncbi.nlm.nih.gov/sites/myncbi/collections/public/1j53ef-4jr6VXs7A-zYHqa7A9/?sort=date&direction=descending
        text: "Pubmed"
      - href: http://scholar.google.ca/citations?hl=en&user=aTyysxgAAAAJ
        text: "Google Scholar"
      - href: cv.qmd
        text: "Curriculum Vitae"
      - file: software_and_web_tools.qmd
        text: "Software and Web Tools"
      - href: resources.qmd
        text: "SAS and R Learning Resources"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

