project:
  type: website
  output-dir: docs
website:
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: "Home"
      - icon: github
        href: https://github.com/stevenhawken
      - icon: twitter
        href: https://twitter.com/stevenhawken
      - href: http://www.ncbi.nlm.nih.gov/sites/myncbi/collections/public/1j53ef-4jr6VXs7A-zYHqa7A9/?sort=date&amp;direction=descending
        text: "Pubmed link"
      - href:  http://scholar.google.ca/citations?hl=en&amp;user=aTyysxgAAAAJ 
        text:  "Google Scholar link"
      - file:  shawken_CV.pdf 
        text:  "Curriculum Vitae"
      - file:  software_and_web_tools.qmd 
        text:  "Software and Web Tools"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

